cleaning up ingress
replicatedhq/replicated pull request #361
Opened 2024-02-13 22:33 UTC by marccampbell

Add port number, fix display

2024-02-13 23:40 UTC, jdewinne requested changes

2024-02-13 23:40 UTC, jdewinne commented on cli/cmd/cluster_addon_ingress_create.go
> +	cmd.Flags().StringVar(&r.args.clusterCreateIngressNamespace, "namespace", "default", "The namespace at the target service is in")
```suggestion
	cmd.Flags().StringVar(&r.args.clusterCreateIngressNamespace, "namespace", "default", "The namespace the target service is in")
```

2024-02-13 23:53 UTC, marccampbell commented on cli/cmd/cluster_addon_ingress_create.go
> +	cmd.Flags().StringVar(&r.args.clusterCreateIngressNamespace, "namespace", "default", "The namespace at the target service is in")
Thanks, updated

2024-02-14 16:40 UTC, jdewinne approved these changes

2024-02-14 16:50 UTC, merged