Adding cmd for creating postgres addon
replicatedhq/replicated pull request #378
Opened 2024-04-09 15:51 UTC by jdewinne

2024-04-11 03:39 UTC, emosbaugh requested changes

2024-04-11 03:39 UTC, emosbaugh commented on cli/cmd/cluster_addon_create_postgres.go
> +	cmd.Flags().BoolVar(&args.dryRun, "dry-run", false, "Dry run")
Can you copy from here? https://github.com/replicatedhq/replicated/blob/main/cli/cmd/cluster_addon_create_objectstore.go#L60-L62

2024-04-11 23:39 UTC, emosbaugh approved these changes

2024-04-11 23:40 UTC, emosbaugh requested changes

2024-04-11 23:40 UTC, emosbaugh commented on pkg/types/cluster.go
> +	Password string `json:"password,omitempty"`
can we remove these? i dont think they are useful

2024-04-12 01:20 UTC, emosbaugh submitted a review, later dismissed

2024-04-16 14:41 UTC, FourSigma approved these changes

2024-04-16 21:16 UTC, marccampbell approved these changes

2024-04-17 13:53 UTC, merged